# cloudbuild.yaml

steps:
# Step 0: DEBUG - Check if the secret is being loaded.
# This step will print the first few characters of the secret to the log.
# This helps confirm if the IAM permission and secret name are correct.
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "--- DEBUG STEP ---"
    if [ -z "$_FIREBASE_CONFIG" ]; then
      echo "ERROR: _FIREBASE_CONFIG is empty or not set. Check secret name in this file and IAM permissions."
      exit 1
    else
      echo "_FIREBASE_CONFIG is set. First 30 characters: $(echo $_FIREBASE_CONFIG | head -c 30)"
      echo "--- END DEBUG ---"
    fi
  secretEnv: ['_FIREBASE_CONFIG']

# Step 1: Build the Docker image.
# We are now securely passing the Firebase service account config as a "build-arg".
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=gcr.io/$PROJECT_ID/my-app:$COMMIT_SHA'
    # The --build-arg flag makes the secret available to the Dockerfile during the build.
    - '--build-arg'
    - 'FIREBASE_SERVICE_ACC_CONFIG=${_FIREBASE_CONFIG}'
    - '.'
  # This 'secretEnv' block makes the secret's value available as an environment variable
  # named _FIREBASE_CONFIG, but ONLY for this build step.
  secretEnv: ['_FIREBASE_CONFIG']

# Step 2: Push the built image to Google Container Registry (GCR).
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my-app:$COMMIT_SHA']

# 3. (Optional) Make the image name available to subsequent build steps.
images:
- 'gcr.io/$PROJECT_ID/my-app:$COMMIT_SHA'

# 4. Specify the logging option.
options:
  logging: CLOUD_LOGGING_ONLY

# 5. Define the secret to be used by this build.
availableSecrets:
  secretManager:
  # This tells Cloud Build to fetch the latest version of your secret.
  # This MUST match the name you gave the secret in Secret Manager.
  - versionName: projects/$PROJECT_ID/secrets/firebase-service-account/versions/latest
    # This maps the secret's value to the environment variable '_FIREBASE_CONFIG'
    env: '_FIREBASE_CONFIG'
